### ISSUE TITLE
Support for Bidirectional Relationships

### ISSUE THREAD

**Issue by lohengrin332** [Ovid/dbix-class-easyfixture#8]
Say you have an Album entity:
```sql
CREATE TABLE album (
    album_id INTEGER PRIMARY KEY AUTOINCREMENT,
    producer_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    ...
    FOREIGN KEY(producer_id) REFERENCES person(person_id) DEFERRABLE INITIALLY DEFERRED
)
```

And a person entity:
```sql
CREATE TABLE person (
    person_id INTEGER PRIMARY KEY AUTOINCREMENT,
    favorite_album_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    ...
    FOREIGN KEY(favorite_album_id) REFERENCES Album(album_id) DEFERRABLE INITIALLY DEFERRED
)
```

Assume Rick Rubin produced the album La Futura by ZZ Top, and it is also his favorite album.  The DBIx code to create these entities would be:
```perl
my $la_futura = $schema->resultset('Album')->create({
    name => 'La Futura',
});
my $rick_rubin = $la_futura->create_related('producer', {
    name => 'Rick Rubin',
});
$rick_rubin->favorite_album($la_futura);
```

This type of bi-directional relationship does not appear to be supported by DBIx::Class::EasyFixture.

My suggestion to resolve this issue is by handling a `deferred` key in the `requires` hash:
```perl
my %definition_for = (
    'la_futura' => {
        new => 'Album',
        requires => {
            'rick_rubin' => {
                our => 'producer_id',
                their => 'person_id',
            },
        },
        using => {
            name => 'La Futura',
        },
    },

    'rick_rubin' => {
        new => 'Person',
        requires => {
            'la_futura' => {
                our => 'favorite_album_id',
                their => 'album_id',
                deferred => 1,
            },
        },
        using => {
            name => 'Rick Rubin',
        },
    },
);
```

If a required entity is flagged as `deferred`, this causes the handling of the required entity to be deferred, as if it were included in the `next` array, while the current entity is created first, as if the given required entity were not present in the `requires` hash.  Once both entities have been created, the relationship between the two is filled in.

If you think this is a good approach to resolving this issue, would you like me to work on a pull request?

**Comment by Ovid** [comment]
I would love to see a pull request for that. My main question is this: how does a programmer know which side of the bi-directional relationship should be deferred? Is it arbitrary? That gives me pause.

**Comment by lohengrin332** [comment]
In a word, yes.  If both sides of a bi-directional relationship are deferrable then the developer would need to decide which side of the relationship to defer.  In my example, the end result would ultimately be the same in the following three scenarios:

1. The developer chooses to mark the `rick_rubin->favorite_album(la_futura)` relationship as `deferred`.
2. The developer chooses to mark the `la_futura->producer(rick_rubin)` relationship as `deferred`.
3. The developer chooses to mark both relationships as `deferred`.

Of course if one side of the relationship is non-deferrable then the developer would need to mark only the other side of the relationship as `deferred`, lest exceptions be raised.
